### ISSUE TITLE
Previous/next links

### ISSUE THREAD

**Issue by aditsu** [pdurbin/philbot#1]
There are "previous day" and "next day" links on most pages when browsing the logs, but some days seem to be missing from the index and the links are missing for those days too. E.g. http://irclog.greptilian.com/friendlyjava/2016-08-11 has no "previous" nor "next" because days 10 and 12 are not there. http://irclog.greptilian.com/friendlyjava/2016-08-10 is empty but it has a "next day" link; inexplicably, it has no "previous day" link although day 9 is recorded.
There should be "previous day" and "next day" links on every page, except maybe the very first and last day in the whole history. The links could potentially "skip" missing days.

**Comment by pdurbin** [comment]
Yeah, here's a screenshot of how it looks. No "← Previous day" or "Next day →" links. Annoying:

![screen shot 2017-02-17 at 11 03 19 pm](https://cloud.githubusercontent.com/assets/21006/23090176/5c7ebb76-f565-11e6-9edb-3d0fade23238.png)

**Comment by pdurbin** [comment]
@aditsu in e052fec I went for a simple fix, to always show the previous and next links. Thanks for bringing this to my attention. Lemme know if this doesn't meet your needs.

**Comment by pdurbin** [comment]
Whoops, I reverted my fix since @aditsu pointed out it didn't work, [saying](http://irclog.greptilian.com/sourcefu/2017-02-18), "now the prev/next links on http://irclog.greptilian.com/friendlyjava/2016-08-11 go to the same page."

**Comment by pdurbin** [comment]
@aditsu ok, I pushed a better fix at 9d358be. If it doesn't work, please let me know. Thanks!
